version: "3.4"

services:
  k6_experiments:
    command: ["tail", "-f", "/var/log/*"]
    container_name: k6_experiments
    image: loadimpact/k6:latest
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://k6_experiments_influxdb:8086/k6
    networks:
      - k6-experiments
    links:
      - k6_experiments_influxdb
      - k6_experiments_grafana
  #    working_dir: /var/www/html
    volumes:
      - ./:/app

  k6_experiments_influxdb:
    container_name: k6_experiments_influxdb
    hostname: k6_experiments_influxdb
    image: influxdb:latest
    environment:
      INFLUXDB_DATA_ENGINE: "tsm1"
      INFLUXDB_REPORTING_DISABLED: "false"
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    networks:
      - k6-experiments
    volumes:
      - k6_experiments_influxdb_volume:/var/lib/influxdb

  k6_experiments_grafana:
    container_name: k6_experiments_grafana
    hostname: k6_experiments_grafana
    image: grafana/grafana:latest
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource"
    ports:
      - "3000:3000"
    user: "0"
    links:
      - k6_experiments_influxdb
    networks:
      - k6-experiments
    volumes:
      - k6_experiments_grafana_volume:/var/lib/grafana

volumes:
  k6_experiments_influxdb_volume:
    driver: local
  k6_experiments_grafana_volume:
    driver: local

networks:
  k6-experiments:
    external: true
